import {
  bathroom9669,
  bathtub9669,
  closet9669,
  familyRoom9669,
  garage9669,
  kitchen9669,
  livingRoom9669,
  main9669,
  nightShot9669,
  court9669,
} from "../../../assets/Miami-Dade/9669-images";
import {
  aerial9765,
  bathroom9765,
  front9765,
  kitchen9765,
  livingRoom9765,
  main9765,
  nightBackshot9765,
  nightTables9765,
  room9765,
} from "../../../assets/Miami-Dade/9765-images";
import {
  famRoom11035,
  kitchen11035,
  kitchenTwo11035,
  livingRooom11035,
  main11035,
} from "../../../assets/Miami-Dade/11035-images";
import {
  bathroom6290,
  kitchen6290,
  livingRoom6290,
  main6290,
  kitchenTwo6290,
  pool6290,
} from "../../../assets/Pinecrest/6290-images";
import { backPool6700, main6700 } from "../../../assets/Pinecrest/6700-images";
import {
  backPool10801,
  main10801,
} from "../../../assets/Pinecrest/10801-images";

//* Properties Below

export const propertiesObj = {
  "miami-dade": [
    {
      id: 1,
      address: "9669 SW 96 ST",
      location: "miami-dade",
      status: "SOLD",
      images: [
        main9669,
        bathroom9669,
        bathtub9669,
        closet9669,
        familyRoom9669,
        garage9669,
        kitchen9669,
        livingRoom9669,
        nightShot9669,
        court9669,
      ],
      description: `Luxury residence located at 17133 Ericarose Court, in Boca Raton's prestigious St. Andrews Country Club. Designed by Hollub Group, it features 6 bedrooms, 8.2 bathrooms, an office, a gym, and a media room. The gourmet kitchen and dual-bath master suite are strikingly elegant. It offers over 11.954 square feet of construction on a 0.37-acre lot. Resort-like exterior with a pool, spa, summer kitchen, and lake views. Includes an elevator, a 3-car garage, and high-end finishes throughout.`,
      sellPrice: "$3,950,000",
      beds: 6,
      baths: 6,
      livingArea: "7,957",
    },
    {
      id: 2,
      address: "9765 SW 110 ST",
      location: "miami-dade",
      status: "SOLD",
      images: [
        main9765,
        aerial9765,
        bathroom9765,
        front9765,
        kitchen9765,
        livingRoom9765,
        nightBackshot9765,
        nightTables9765,
        room9765,
      ],
      description: `Luxury residence located at 17133 Ericarose Court, in Boca Raton's prestigious St. Andrews Country Club. Designed by Hollub Group, it features 6 bedrooms, 8.2 bathrooms, an office, a gym, and a media room. The gourmet kitchen and dual-bath master suite are strikingly elegant. It offers over 11.954 square feet of construction on a 0.37-acre lot. Resort-like exterior with a pool, spa, summer kitchen, and lake views. Includes an elevator, a 3-car garage, and high-end finishes throughout.`,
      sellPrice: "$4,050,000",
      beds: 5,
      baths: 7,
      livingArea: "5,846",
    },
    {
      id: 3,
      address: "11035 SW 93 ST",
      location: "miami-dade",
      status: "SOLD",
      images: [
        main11035,
        famRoom11035,
        kitchen11035,
        kitchenTwo11035,
        livingRooom11035,
      ],
      description: `Luxury residence located at 17133 Ericarose Court, in Boca Raton's prestigious St. Andrews Country Club. Designed by Hollub Group, it features 6 bedrooms, 8.2 bathrooms, an office, a gym, and a media room. The gourmet kitchen and dual-bath master suite are strikingly elegant. It offers over 11.954 square feet of construction on a 0.37-acre lot. Resort-like exterior with a pool, spa, summer kitchen, and lake views. Includes an elevator, a 3-car garage, and high-end finishes throughout.`,
      sellPrice: "$4,900,000",
      beds: "6",
      baths: "7",
      livingArea: "5,086",
    },
  ],

  pinecrest: [
    {
      id: 4,
      address: "6290 SW 130 TER",
      location: "PINECREST",
      status: "RENTED",
      images: [
        main6290,
        bathroom6290,
        kitchen6290,
        livingRoom6290,
        kitchenTwo6290,
        pool6290,
      ],
      description: `Luxury residence located at 17133 Ericarose Court, in Boca Raton's prestigious St. Andrews Country Club. Designed by Hollub Group, it features 6 bedrooms, 8.2 bathrooms, an office, a gym, and a media room. The gourmet kitchen and dual-bath master suite are strikingly elegant. It offers over 11.954 square feet of construction on a 0.37-acre lot. Resort-like exterior with a pool, spa, summer kitchen, and lake views. Includes an elevator, a 3-car garage, and high-end finishes throughout.`,
      sellPrice: "$35,000/mo",
      beds: 7,
      baths: 8,
      livingArea: "7,028",
    },
    {
      id: 5,
      address: "6700 SW 115 ST, PINECREST, FL 33156, United States",
      location: "PINECREST",
      status: "SOLD",
      images: [main6700, backPool6700],
      description: `Luxury residence located at 17133 Ericarose Court, in Boca Raton's prestigious St. Andrews Country Club. Designed by Hollub Group, it features 6 bedrooms, 8.2 bathrooms, an office, a gym, and a media room. The gourmet kitchen and dual-bath master suite are strikingly elegant. It offers over 11.954 square feet of construction on a 0.37-acre lot. Resort-like exterior with a pool, spa, summer kitchen, and lake views. Includes an elevator, a 3-car garage, and high-end finishes throughout.`,
      sellPrice: "$2,995,000",
      beds: 4,
      baths: 4,
      livingArea: "3,931",
    },
    {
      id: 6,
      address: "10801 SW 67 AVE",
      location: "PINECREST",
      status: "SOLD",
      images: [main10801, backPool10801],
      description: `Luxury residence located at 17133 Ericarose Court, in Boca Raton's prestigious St. Andrews Country Club. Designed by Hollub Group, it features 6 bedrooms, 8.2 bathrooms, an office, a gym, and a media room. The gourmet kitchen and dual-bath master suite are strikingly elegant. It offers over 11.954 square feet of construction on a 0.37-acre lot. Resort-like exterior with a pool, spa, summer kitchen, and lake views. Includes an elevator, a 3-car garage, and high-end finishes throughout.`,
      sellPrice: "$10,700,000",
      beds: 7,
      baths: 10,
      livingArea: "8,990",
    },
  ],
};


